[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = [
  "cd backend && pnpm install"
]

[phases.build]
cmds = [
  "cd backend && pnpm build && cd backend && pnpm prisma generate"
]

[start]
cmd = "cd backend && pnpm start"

